In [4]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits

digits = load_digits()

In [6]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [15]:
lr = LogisticRegression(max_iter=1000)
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.9777777777777777

In [16]:
svm = SVC()
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.9907407407407407

In [17]:
rf = RandomForestClassifier(n_estimators=40)
rf.fit(x_train, y_train)
rf.score(x_test, y_test)

0.9777777777777777

In [22]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [24]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [25]:
def get_score(model, x_train, x_test, y_train, y_test):
    model.fit(x_train, y_train)
    return model.score(x_test, y_test)

In [27]:
from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

In [31]:
score_l = []
score_svm = []
score_rf = []

for train_index, test_index in kf.split(digits.data):
    x_train, x_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    score_l.append(get_score(LogisticRegression(max_iter=1000), x_train, x_test, y_train, y_test))
    score_svm.append(get_score(SVC(), x_train, x_test, y_train, y_test))
    score_rf.append(get_score(RandomForestClassifier(), x_train, x_test, y_train, y_test))


In [32]:
score_l

[0.9248747913188647, 0.9432387312186978, 0.9148580968280468]

In [34]:
score_svm

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]

In [35]:
score_rf

[0.9449081803005008, 0.9465776293823038, 0.9248747913188647]

In [36]:
from sklearn.model_selection import cross_val_score

In [42]:
cross_val_score(RandomForestClassifier(n_estimators=40), digits.data, digits.target)

array([0.93333333, 0.91944444, 0.95821727, 0.95821727, 0.92479109])

In [43]:
cross_val_score(SVC(), digits.data, digits.target)

array([0.96111111, 0.94444444, 0.98328691, 0.98885794, 0.93871866])

In [44]:
cross_val_score(LogisticRegression(max_iter=1000), digits.data, digits.target)

array([0.92222222, 0.86944444, 0.94150418, 0.94150418, 0.89693593])